import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function MarketingLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<header className='max-w[1170px] mx-auto bg-blue-300 p-[1rem] sticky top-0'>Header</header>
				{children}
				<footer className='bg-amber-200 p-[1rem]'>Footer</footer>
			</body>
		</html>
	)
}
